# Generated by Django 4.2.16 on 2024-10-15 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('treatment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicine',
            options={'verbose_name': '', 'verbose_name_plural': 'Medicines'},
        ),
        migrations.AlterModelOptions(
            name='treatment',
            options={'verbose_name': '', 'verbose_name_plural': 'Treatments'},
        ),
    ]
