# Generated by Django 4.2.16 on 2024-10-04 00:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('treatment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Especie',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animal.species')),
            ],
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('number', models.PositiveIntegerField()),
                ('weight', models.PositiveIntegerField()),
                ('file', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('breed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animal.breed')),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animal.species')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animal.status')),
                ('treatment', models.ManyToManyField(blank=True, to='treatment.treatment')),
            ],
        ),
    ]
