# Generated by Django 3.2.25 on 2024-10-02 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='species',
            options={'verbose_name_plural': 'Especie'},
        ),
        migrations.RemoveField(
            model_name='species',
            name='breed',
        ),
        migrations.AddField(
            model_name='species',
            name='breed',
            field=models.ManyToManyField(blank=True, null=True, to='animal.Breed'),
        ),
    ]
