# Generated by Django 3.2.25 on 2024-10-02 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0004_auto_20241001_2334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='breed',
        ),
        migrations.RemoveField(
            model_name='breed',
            name='species',
        ),
        migrations.AddField(
            model_name='species',
            name='breed',
            field=models.ManyToManyField(blank=True, null=True, to='animal.Breed'),
        ),
    ]
