# Generated by Django 3.2.25 on 2024-10-02 04:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0005_auto_20241001_2334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='species',
            name='breed',
        ),
        migrations.AddField(
            model_name='animal',
            name='breed',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='animal.breed'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='breed',
            name='species',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='animal.species'),
            preserve_default=False,
        ),
    ]
