# Generated by Django 3.2.25 on 2024-10-02 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treatment', '0001_initial'),
        ('animal', '0006_auto_20241001_2335'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='treatment',
            field=models.ManyToManyField(blank=True, null=True, to='treatment.Treatment'),
        ),
    ]
